checks:
    javascript: true

filter:
    excluded_paths:
        - coverage/*


build:
    environment:
        mongodb: '3.2'
        node: v8.9.1
    tests:
        override:
            -
                #command: 'istanbul cover --report clover test.js'
                command: 'npm run test-scrutinizer'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
