checks:
    javascript: true

filter:
    excluded_paths:
        - coverage/*

build:
    nodes:
        analysis:
            environment:
                mongodb: true
                node:
                    version: 8.9.1
        tests: true
    environment:
        node: 8.9.1

    dependencies:
        before:
            command: nvm install node

    tests:
        override:
            -
                command: 'npm run test-scrutinizer'
                coverage:
                    file: 'build/coverage/clover.xml'
                    format: 'clover'
