checks:
    javascript: true

build:
    environment:
        mongodb: true

    dependencies:
        before:
            command: nvm install node

    tests:
        override:
            -
                command: 'npm run test'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
