checks:
    javascript: true

filter:
    excluded_paths:

build:
    environment:
        mongodb: '3.2'
        node: v8.9.1
    tests:
        override:
            -
                command: 'npm run coverage-scrut'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
